### ISSUE TITLE
Some things I noticed

### ISSUE THREAD

**Issue by ThiefMaster** [bpedersen2/indico-mlz-export#1]
`@HTTPAPIHook.register` - don't use that in a plugin; call `HTTPAPIHook.register(MLZExportRegistrationsHook)` in your plugin's `init` method instead. Otherwise it'd be registered in case the file gets imported without the plugin being actually enabled.

---

    if not Event(self.eventId).can_manage(request.oauth.user, permission='registration')

This shouldn't work at all. The `Event` constructor accepts no positional arguments, and you need to actually get the event from the database. So you want `Event.get(self.eventId)` (also, style advice: better call it `event_id`; camelCase is not popular in the Python world)

**Comment by bpedersen2** [comment]
Thanks for  the comments. 
As for the can_manage part, I found this by git grep in core:
indico/modules/events/registration/__init__.py:    if not event.can_manage(session.user, 'registration'):
indico/modules/events/registration/__init__.py:    if event.can_manage(session.user, permission='registration'):
indico/modules/events/registration/api.py:        if not self.event.can_manage(request.oauth.user, permission='registration'):
indico/modules/events/registration/api.py:        if not self.event.can_manage(request.oauth.user, permission='registration'):

**Comment by ThiefMaster** [comment]
The `can_manage` call is fine - just the `Event(self.eventId)` isn't.

**Comment by bpedersen2** [comment]
fixed now
